'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { autoGenerateTitle, autoGenerateDescription } from '@/lib/seoMetadata';

interface Story {
  id: string;
  slug: string;
  title: string;
  description?: string;
  is_published: boolean;
}

interface SEOData {
  id: string;
  slug: string;
  title: string;
  description?: string;
  meta_title?: string;
  meta_description?: string;
  meta_keywords?: string[];
  og_image_url?: string;
  seo_category?: string;
  age_rating?: string;
  duration_minutes?: number;
  language?: string;
  price?: number;
  is_free?: boolean;
  validation?: {
    meta_title?: { valid: boolean; length: number; message?: string };
    meta_description?: { valid: boolean; length: number; message?: string };
  };
}

export default function SEOAdmin() {
  const router = useRouter();
  const [stories, setStories] = useState<Story[]>([]);
  const [selectedStory, setSelectedStory] = useState<string>('');
  const [seoData, setSeoData] = useState<SEOData | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [formData, setFormData] = useState({
    meta_title: '',
    meta_description: '',
    meta_keywords: '',
    og_image_url: '',
    seo_category: '',
    age_rating: '',
    duration_minutes: '',
    language: 'da',
  });

  // Check if user is logged in via server session
  useEffect(() => {
    const checkSession = async () => {
      try {
        const response = await fetch('/api/admin/session', {
          method: 'GET',
          credentials: 'include',
        });
        if (!response.ok) {
          router.push('/admin/login');
        }
      } catch (error) {
        console.error('Session check failed:', error);
        router.push('/admin/login');
      }
    };
    checkSession();
  }, [router]);

  // Load stories on component mount
  useEffect(() => {
    loadStories();
  }, []);

  // Load SEO data when story is selected
  useEffect(() => {
    if (selectedStory) {
      loadSEOData(selectedStory);
    } else {
      setSeoData(null);
      resetForm();
    }
  }, [selectedStory]);

  const loadStories = async () => {
    try {
      const response = await fetch('/api/admin/stories', {
        credentials: 'include',
      });
      if (response.ok) {
        const data = await response.json();
        setStories(data);
      }
    } catch (error) {
      console.error('Failed to load stories:', error);
    } finally {
      setLoading(false);
    }
  };

  const loadSEOData = async (storyId: string) => {
    try {
      const response = await fetch(`/api/admin/seo/${storyId}`, {
        credentials: 'include',
      });
      if (response.ok) {
        const data: SEOData = await response.json();
        setSeoData(data);
        setFormData({
          meta_title: data.meta_title || '',
          meta_description: data.meta_description || '',
          meta_keywords: data.meta_keywords ? data.meta_keywords.join(', ') : '',
          og_image_url: data.og_image_url || '',
          seo_category: data.seo_category || '',
          age_rating: data.age_rating || '',
          duration_minutes: data.duration_minutes?.toString() || '',
          language: data.language || 'da',
        });
      } else {
        console.error('Failed to load SEO data');
      }
    } catch (error) {
      console.error('Error loading SEO data:', error);
    }
  };

  const resetForm = () => {
    setFormData({
      meta_title: '',
      meta_description: '',
      meta_keywords: '',
      og_image_url: '',
      seo_category: '',
      age_rating: '',
      duration_minutes: '',
      language: 'da',
    });
  };

  const handleAutoGenerateTitle = () => {
    if (seoData) {
      const generated = autoGenerateTitle(seoData);
      setFormData({ ...formData, meta_title: generated });
    }
  };

  const handleAutoGenerateDescription = () => {
    if (seoData) {
      const generated = autoGenerateDescription(seoData);
      setFormData({ ...formData, meta_description: generated });
    }
  };

  const handleSave = async () => {
    if (!selectedStory) return;

    setSaving(true);
    try {
      const response = await fetch(`/api/admin/seo/${selectedStory}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include',
        body: JSON.stringify(formData),
      });

      if (response.ok) {
        const updated: SEOData = await response.json();
        setSeoData(updated);
        alert('✅ SEO settings saved successfully!');
      } else {
        const error = await response.json();
        alert(`❌ Failed to save: ${error.error || 'Unknown error'}`);
      }
    } catch (error) {
      console.error('Error saving SEO data:', error);
      alert('❌ Failed to save SEO settings');
    } finally {
      setSaving(false);
    }
  };

  const getSEOStatus = (story: Story): 'complete' | 'partial' | 'none' => {
    // This would ideally check if SEO fields are populated
    // For now, we'll show it as "none" until they select the story
    return 'none';
  };

  const getStatusColor = (status: 'complete' | 'partial' | 'none') => {
    switch (status) {
      case 'complete':
        return 'bg-green-100 text-green-800';
      case 'partial':
        return 'bg-yellow-100 text-yellow-800';
      default:
        return 'bg-gray-100 text-gray-800';
    }
  };

  const metaTitleLength = formData.meta_title.length;
  const metaDescriptionLength = formData.meta_description.length;

  return (
    <div className="min-h-screen bg-gray-100 py-8">
      <div className="max-w-6xl mx-auto px-4">
        <div className="bg-white rounded-lg shadow-lg p-8">
          <div className="flex justify-between items-center mb-8">
            <h1 className="text-3xl font-bold text-gray-900">
              🔍 SEO Management
            </h1>
            <button
              onClick={() => router.push('/admin')}
              className="bg-gray-600 text-white px-4 py-2 rounded-md hover:bg-gray-700"
            >
              ← Back to Dashboard
            </button>
          </div>

          {/* Story Selection */}
          <div className="mb-8">
            <label className="block text-sm font-medium text-gray-900 mb-2">
              Select Story
            </label>
            <select
              value={selectedStory}
              onChange={(e) => setSelectedStory(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
            >
              <option value="">-- Select a story --</option>
              {stories.map((story) => (
                <option key={story.id} value={story.slug || story.id}>
                  {story.title} {story.is_published ? '✅' : '📝'}
                </option>
              ))}
            </select>
          </div>

          {loading ? (
            <div className="text-center py-8">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
              <p className="text-gray-600 mt-2">Loading stories...</p>
            </div>
          ) : selectedStory && seoData ? (
            <div className="space-y-6">
              {/* Meta Title */}
              <div>
                <div className="flex justify-between items-center mb-2">
                  <label className="block text-sm font-medium text-gray-900">
                    Meta Title
                  </label>
                  <div className="flex gap-2">
                    <button
                      onClick={handleAutoGenerateTitle}
                      className="text-xs bg-blue-100 text-blue-700 px-2 py-1 rounded hover:bg-blue-200"
                    >
                      ✨ Auto-generate
                    </button>
                    <span
                      className={`text-xs px-2 py-1 rounded ${
                        metaTitleLength >= 50 && metaTitleLength <= 60
                          ? 'bg-green-100 text-green-700'
                          : metaTitleLength < 30 || metaTitleLength > 60
                          ? 'bg-red-100 text-red-700'
                          : 'bg-yellow-100 text-yellow-700'
                      }`}
                    >
                      {metaTitleLength} / 60 chars
                    </span>
                  </div>
                </div>
                <input
                  type="text"
                  value={formData.meta_title}
                  onChange={(e) => setFormData({ ...formData, meta_title: e.target.value })}
                  placeholder={seoData.title}
                  maxLength={60}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
                />
                <p className="text-xs text-gray-500 mt-1">
                  Recommended: 50-60 characters. Falls back to story title if empty.
                </p>
              </div>

              {/* Meta Description */}
              <div>
                <div className="flex justify-between items-center mb-2">
                  <label className="block text-sm font-medium text-gray-900">
                    Meta Description
                  </label>
                  <div className="flex gap-2">
                    <button
                      onClick={handleAutoGenerateDescription}
                      className="text-xs bg-blue-100 text-blue-700 px-2 py-1 rounded hover:bg-blue-200"
                    >
                      ✨ Auto-generate
                    </button>
                    <span
                      className={`text-xs px-2 py-1 rounded ${
                        metaDescriptionLength >= 150 && metaDescriptionLength <= 160
                          ? 'bg-green-100 text-green-700'
                          : metaDescriptionLength < 120 || metaDescriptionLength > 160
                          ? 'bg-red-100 text-red-700'
                          : 'bg-yellow-100 text-yellow-700'
                      }`}
                    >
                      {metaDescriptionLength} / 160 chars
                    </span>
                  </div>
                </div>
                <textarea
                  value={formData.meta_description}
                  onChange={(e) => setFormData({ ...formData, meta_description: e.target.value })}
                  placeholder={seoData.description || 'An interactive story adventure...'}
                  maxLength={160}
                  rows={3}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
                />
                <p className="text-xs text-gray-500 mt-1">
                  Recommended: 150-160 characters. Falls back to story description if empty.
                </p>
              </div>

              {/* Keywords */}
              <div>
                <label className="block text-sm font-medium text-gray-900 mb-2">
                  Keywords (comma-separated)
                </label>
                <input
                  type="text"
                  value={formData.meta_keywords}
                  onChange={(e) => setFormData({ ...formData, meta_keywords: e.target.value })}
                  placeholder="interactive story, kids adventure, voice narration"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
                />
                <p className="text-xs text-gray-500 mt-1">
                  Enter 3-5 keywords separated by commas.
                </p>
              </div>

              {/* OG Image URL */}
              <div>
                <label className="block text-sm font-medium text-gray-900 mb-2">
                  Open Graph Image URL
                </label>
                <input
                  type="url"
                  value={formData.og_image_url}
                  onChange={(e) => setFormData({ ...formData, og_image_url: e.target.value })}
                  placeholder="https://example.com/image.jpg"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
                />
                {formData.og_image_url && (
                  <div className="mt-2">
                    <img
                      src={formData.og_image_url}
                      alt="OG Preview"
                      className="max-w-xs border border-gray-300 rounded"
                      onError={(e) => {
                        (e.target as HTMLImageElement).style.display = 'none';
                      }}
                    />
                  </div>
                )}
                <p className="text-xs text-gray-500 mt-1">
                  Recommended: 1200x630px. Falls back to cover image if empty.
                </p>
              </div>

              {/* SEO Category */}
              <div>
                <label className="block text-sm font-medium text-gray-900 mb-2">
                  Category (for Google Shopping)
                </label>
                <select
                  value={formData.seo_category}
                  onChange={(e) => setFormData({ ...formData, seo_category: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
                >
                  <option value="">-- Select category --</option>
                  <option value="Adventure">Adventure</option>
                  <option value="Fantasy">Fantasy</option>
                  <option value="Educational">Educational</option>
                  <option value="Fairy Tale">Fairy Tale</option>
                  <option value="Mystery">Mystery</option>
                  <option value="Science Fiction">Science Fiction</option>
                  <option value="Historical">Historical</option>
                  <option value="Other">Other</option>
                </select>
              </div>

              {/* Age Rating */}
              <div>
                <label className="block text-sm font-medium text-gray-900 mb-2">
                  Age Rating
                </label>
                <select
                  value={formData.age_rating}
                  onChange={(e) => setFormData({ ...formData, age_rating: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
                >
                  <option value="">-- Select age rating --</option>
                  <option value="All Ages">All Ages</option>
                  <option value="3+">3+</option>
                  <option value="6+">6+</option>
                  <option value="9+">9+</option>
                  <option value="12+">12+</option>
                </select>
              </div>

              {/* Duration */}
              <div>
                <label className="block text-sm font-medium text-gray-900 mb-2">
                  Duration (minutes)
                </label>
                <input
                  type="number"
                  value={formData.duration_minutes}
                  onChange={(e) => setFormData({ ...formData, duration_minutes: e.target.value })}
                  placeholder="15"
                  min="1"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
                />
              </div>

              {/* Language */}
              <div>
                <label className="block text-sm font-medium text-gray-900 mb-2">
                  Language
                </label>
                <select
                  value={formData.language}
                  onChange={(e) => setFormData({ ...formData, language: e.target.value })}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900"
                >
                  <option value="da">Danish (da)</option>
                  <option value="en">English (en)</option>
                </select>
              </div>

              {/* Save Button */}
              <div className="flex justify-end gap-4 pt-4 border-t">
                <button
                  onClick={() => setSelectedStory('')}
                  className="px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSave}
                  disabled={saving}
                  className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:bg-gray-400 disabled:cursor-not-allowed"
                >
                  {saving ? 'Saving...' : '💾 Save SEO Settings'}
                </button>
              </div>

              {/* Validation Feedback */}
              {seoData.validation && (
                <div className="mt-4 p-4 bg-gray-50 border border-gray-200 rounded">
                  <h3 className="text-sm font-semibold text-gray-900 mb-2">Validation Status</h3>
                  {seoData.validation.meta_title && (
                    <div className={`text-xs mb-1 ${seoData.validation.meta_title.valid ? 'text-green-700' : 'text-red-700'}`}>
                      Title: {seoData.validation.meta_title.length} chars
                      {seoData.validation.meta_title.message && ` - ${seoData.validation.meta_title.message}`}
                    </div>
                  )}
                  {seoData.validation.meta_description && (
                    <div className={`text-xs ${seoData.validation.meta_description.valid ? 'text-green-700' : 'text-red-700'}`}>
                      Description: {seoData.validation.meta_description.length} chars
                      {seoData.validation.meta_description.message && ` - ${seoData.validation.meta_description.message}`}
                    </div>
                  )}
                </div>
              )}
            </div>
          ) : (
            <div className="text-center py-8 text-gray-500">
              Select a story to manage its SEO settings
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
