import OpenAI from 'openai';
import Replicate from 'replicate';

// Initialize AI services
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
});

export interface ImageGenerationOptions {
  model?: 'dalle3'; // Only DALL-E 3 is supported
  size?: '1024x1024' | '1024x1792' | '1792x1024';
  quality?: 'standard' | 'hd';
  style?: 'vivid' | 'natural';
  n?: number;
}

export interface GeneratedImage {
  url: string;
  revised_prompt?: string;
  model: string;
  size: string;
  cost?: number;
}

/**
 * Generate an image using DALL-E 3
 */
export async function generateImageWithDALLE3(
  prompt: string,
  options: ImageGenerationOptions = {}
): Promise<GeneratedImage> {
  try {
    console.log('🎨 Generating image with DALL-E 3:', prompt);
    
    const response = await openai.images.generate({
      model: 'dall-e-3',
      prompt,
      size: options.size || '1024x1024',
      quality: options.quality || 'standard',
      style: options.style || 'vivid',
      n: 1,
    });

    if (!response.data || response.data.length === 0) {
      throw new Error('No image generated by DALL-E 3');
    }

    const image = response.data[0];
    
    return {
      url: image.url!,
      revised_prompt: image.revised_prompt,
      model: 'dall-e-3',
      size: options.size || '1024x1024',
      cost: 0.04, // DALL-E 3 cost per image
    };
  } catch (error) {
    console.error('❌ DALL-E 3 generation error:', error);
    throw new Error(`DALL-E 3 generation failed: ${error}`);
  }
}

/**
 * @deprecated Stable Diffusion is no longer supported. Use DALL-E 3 instead.
 * This function is kept for backwards compatibility but will not be used.
 */
export async function generateImageWithStableDiffusion(
  prompt: string,
  options: ImageGenerationOptions = {}
): Promise<GeneratedImage> {
  // Redirect to DALL-E 3 instead
  console.warn('⚠️ Stable Diffusion is deprecated. Using DALL-E 3 instead.');
  return generateImageWithDALLE3(prompt, options);
}

/**
 * Generate an image using DALL-E 3 (OpenAI API)
 */
export async function generateImage(
  prompt: string,
  options: ImageGenerationOptions = {}
): Promise<GeneratedImage> {
  // Always use DALL-E 3 for image generation
  return generateImageWithDALLE3(prompt, options);
}

/**
 * Generate multiple images with the same prompt
 */
export async function generateMultipleImages(
  prompt: string,
  count: number,
  options: ImageGenerationOptions = {}
): Promise<GeneratedImage[]> {
  const promises = Array(count).fill(null).map(() => 
    generateImage(prompt, options)
  );
  
  return Promise.all(promises);
}

/**
 * Analyze previous images to extract visual style and character appearance
 */
async function analyzePreviousImages(imageUrls: string[]): Promise<string> {
  if (!imageUrls || imageUrls.length === 0) {
    return '';
  }

  try {
    console.log('🔍 Analyzing previous images for visual consistency...');
    
    // Use GPT-4 Vision to analyze the images
    const imageAnalysisPromises = imageUrls.map(async (imageUrl) => {
      try {
        const response = await openai.chat.completions.create({
          model: 'gpt-4o-mini', // Using mini for cost efficiency
          messages: [
            {
              role: 'user',
              content: [
                {
                  type: 'text',
                  text: 'Analyze this story illustration image. Describe: 1) The art style (e.g., Disney, watercolor, digital painting), 2) Character appearances (clothing, features, colors), 3) Color palette and lighting, 4) Overall visual atmosphere. Be concise and focus on visual elements that should be consistent in the next scene.'
                },
                {
                  type: 'image_url',
                  image_url: { url: imageUrl }
                }
              ]
            }
          ],
          max_tokens: 200
        });

        return response.choices[0]?.message?.content || '';
      } catch (error) {
        console.warn('⚠️ Failed to analyze image:', imageUrl, error);
        return '';
      }
    });

    const analyses = await Promise.all(imageAnalysisPromises);
    const validAnalyses = analyses.filter(a => a.length > 0);
    
    if (validAnalyses.length > 0) {
      const combinedAnalysis = validAnalyses.join('. ');
      console.log('✅ Image analysis complete:', combinedAnalysis.substring(0, 100));
      return `Maintain visual consistency with previous scenes: ${combinedAnalysis}. `;
    }
  } catch (error) {
    console.warn('⚠️ Image analysis failed:', error);
  }

  return '';
}

/**
 * Create a story-specific image prompt with character consistency and visual reference
 */
export async function createStoryImagePrompt(
  storyText: string,
  storyTitle: string,
  style: string = 'fantasy adventure book illustration',
  characters?: Array<{
    name: string;
    description?: string;
    appearancePrompt?: string;
    role?: string;
    emotion?: string;
    action?: string;
  }>,
  previousImageUrls?: string[]
): Promise<string> {
  // Analyze previous images for visual consistency
  let visualConsistencyNote = '';
  if (previousImageUrls && previousImageUrls.length > 0) {
    visualConsistencyNote = await analyzePreviousImages(previousImageUrls);
  }

  // Build character descriptions
  let characterDescriptions = '';
  if (characters && characters.length > 0) {
    const characterParts = characters.map(char => {
      let desc = char.name;
      if (char.description) desc += ` (${char.description})`;
      if (char.appearancePrompt) desc += `, ${char.appearancePrompt}`;
      if (char.emotion) desc += `, ${char.emotion} expression`;
      if (char.action) desc += `, ${char.action}`;
      return desc;
    });
    characterDescriptions = `, featuring ${characterParts.join(', ')}`;
  }
  
  // Clean up the story text
  const cleanStoryText = storyText
    .replace(/\*\*/g, '') // Remove markdown bold
    .replace(/\*/g, '') // Remove markdown italic
    .replace(/#{1,6}\s/g, '') // Remove markdown headers
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') // Convert markdown links to plain text
    .trim();
  
  // Use up to 400 characters of the story text (reduced to make room for visual consistency note)
  const sceneDescription = cleanStoryText.substring(0, 400).trim();
  
  // Create a comprehensive prompt with visual consistency and story text
  const prompt = `${visualConsistencyNote}${style}: ${sceneDescription}${characterDescriptions}. Detailed, high quality, book illustration style, cinematic lighting, no text, no words, no writing, no letters`;
  
  return prompt;
}


/**
 * Generate a video using Replicate
 */
export async function generateVideoWithReplicate(
  prompt: string,
  imageUrl?: string
): Promise<{ url: string; cost: number }> {
  try {
    console.log('🎬 Generating video with Replicate:', prompt);
    
    // Check if API token is set
    if (!process.env.REPLICATE_API_TOKEN) {
      throw new Error('REPLICATE_API_TOKEN environment variable is not set');
    }
    
    console.log('✅ Replicate API token found');
    
    const Replicate = (await import('replicate')).default;
    const replicate = new Replicate({
      auth: process.env.REPLICATE_API_TOKEN,
    });

    // If we have an image, animate it. Otherwise skip for now.
    if (!imageUrl) {
      throw new Error('Video generation requires an existing image. Generate an image first, then convert it to video.');
    }

    // Use Kling v2.1 to animate an image
    console.log('🎬 Calling Replicate API with Kling v2.1, image:', imageUrl);
    
    // Create and wait for the prediction
    const prediction = await replicate.predictions.create({
      model: "kwaivgi/kling-v2.1",
      input: {
        prompt: prompt.substring(0, 200), // Use story context for video animation
        start_image: imageUrl,
        aspect_ratio: "16:9",
        duration: 5, // 5 second video
        negative_prompt: "blurry, low quality, distorted"
      }
    });

    console.log('🔍 Prediction created:', prediction.id, 'status:', prediction.status);

    // Wait for the prediction to complete
    let finalPrediction = prediction;
    while (finalPrediction.status !== 'succeeded' && finalPrediction.status !== 'failed' && finalPrediction.status !== 'canceled') {
      await new Promise(resolve => setTimeout(resolve, 2000)); // Poll every 2 seconds
      finalPrediction = await replicate.predictions.get(prediction.id);
      console.log('⏳ Prediction status:', finalPrediction.status);
    }

    if (finalPrediction.status === 'failed') {
      throw new Error(`Replicate prediction failed: ${finalPrediction.error}`);
    }

    if (finalPrediction.status === 'canceled') {
      throw new Error('Replicate prediction was canceled');
    }

    console.log('🔍 Final prediction output type:', typeof finalPrediction.output);
    console.log('🔍 Final prediction output:', JSON.stringify(finalPrediction.output, null, 2));

    // Extract video URL from the prediction output
    let videoUrl: string | null = null;
    const output = finalPrediction.output;
    
    if (typeof output === 'string') {
      videoUrl = output;
    } else if (Array.isArray(output) && output.length > 0) {
      videoUrl = output[0];
    } else if (output && typeof output === 'object') {
      videoUrl = (output as any).output || (output as any).url || (output as any)[0];
    }
    
    if (!videoUrl || typeof videoUrl !== 'string') {
      console.error('❌ Could not extract video URL from output:', output);
      throw new Error(`No video URL returned from Replicate. Output type: ${typeof output}, Output: ${JSON.stringify(output)}`);
    }

    console.log('✅ Video generated:', videoUrl);

    return {
      url: videoUrl,
      cost: 0.10, // Approximate cost per video
    };
  } catch (error) {
    console.error('❌ Video generation error:', error);
    throw new Error(`Video generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

// Legacy function name for compatibility
export const generateVideoWithRunway = generateVideoWithReplicate;
